Added base structure of app
Anastasiella/LP_marketplace pull request #1
Opened 2020-09-28 19:51 UTC by Anastasiella

2020-09-28 20:56 UTC, dolfinus requested changes

2020-09-28 20:56 UTC, dolfinus commented on app.py
> +app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
Наверное не стоит модифицировать конфиг в каком-то стороннем классе.

2020-09-28 20:56 UTC, dolfinus commented on app.py
> +def get_items(name):
Согласно REST методологии, URL вида:
```
GET /items
```
должны возвращать список значений, а вот
```
GET/items/:item (например, /items/1
```
должны возвращать один объект по полученному значению (в данном случае - имя).

Соответственно, у тебя либо не должно быть параметра name в URL и аргументах функции, либо функция должна называться `get_item` и отрисовывать шаблон `item.html`.

2020-09-28 20:56 UTC, dolfinus commented on config.py
> +    DEBUG = False
Ммм, такой себе вариант. Лучше завести одну переменную, например, ENV, чем вытаться модифицировать кучу.
К тому же конфиг можно переопределить с помощью переменных окружения, и тогда можно получить нестандартный конфиг.

2020-09-28 20:56 UTC, dolfinus commented on config.py
> +    SQLALCHEMY_DATABASE_URI = "abc"
Рекомендую прописать сюда, например, sqlite базу (просто файлик), чтобы был хоть какой-то рабочий URL. Без него сейчас не будет работать SQLAlchemy.

Обычно для разных окружений используют разные URL - например, отдельный URL на тестовую базу и отдельно на prod.

2020-09-28 20:56 UTC, dolfinus commented on models.py
> +        return '<id {}>'.format(self.user_id)
Вместо id в строке стоит выводить название класса. Тогда при запуске интерпретатора python после ввода команды:
```python
db.query(User).one()
```
ты  увидишь
```
<User 123>
```

Колонка id будет у кучи разных моделей, и их идентификаторы могут быть и не уникальны в контексте всей БД. А вот User с идентификатором 123 вполне себе уникальный объект в БД, и тип сразу видно.

2020-09-28 20:56 UTC, dolfinus commented on static/css/bootstrap-grid.css
> +/*!
Добавь папку static в .gitignore.
А вообще обычно Bootstrap подключают не в виде копии файла в проекте/на машине, а как стиль из внешнего источника, например CDN:
```html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
```

2020-09-29 20:02 UTC, Anastasiella commented on config.py
> +    DEBUG = False
Не совсем поняла что это значит. Объясни пожалуйста поподробнее.

2020-09-29 20:02 UTC, Anastasiella commented
Все поправила, кроме одного config.py

2020-09-29 20:37 UTC, dolfinus approved these changes

2020-09-29 20:37 UTC, dolfinus commented on config.py
> +    DEBUG = False
У тебя сейчас есть 3 переменные:
DEBUG
TESTING
DEVELOPMENT

Все они выглядят как что-то весьма очень похожее, но не совсем.
Допустим, установлена переменная DEBUG. И где-то в коде они проверяется, скажем, в функции логирования - если значение True, то выводится больше логов с дополнительной информацией, но в False будет самый минимум.

При запуске приложения оно получает переменные окружения, а здесь указаны значения-по-умолчанию
И случайно между запусками у переменной DEBUG изменилось значение с False на True. Например, что-то накосячили с командами, и переменная окружения в текущем окне консоли изменилась, и в ней повторно запустили приложение для проверки тестов.

Это боль.

Обычно есть 2 хороших решения:
1. Одна-единственная переменная окружения, например с названием ENV, от значения которой выбирается набор остальных значений. Например, при ENV=production выбирается ProductionConfig, при ENV=testing выбирается TestingConfig. На зависимые от нее переменные можно завязывать условия в коде, если приняло соглашение, что менять можно эту и только эту переменную (ну или код не смотрит на другие).
2. Каждая переменная окружения значит что-то свое, и код проверяет их по отдельности.

Оба варианта дают возможность реализовывать очень гибкие конфиги, поэтому Flask из коробки поддерживает и первый, и второй.

К чему я это все пишу - сейчас в коде все выглядит так, будто используется вариант 1 (только с другим названием переменной, обычно это FLASK_ENV, см https://flask.palletsprojects.com/en/1.1.x/config/).

Вот только здесь:
https://github.com/Anastasiella/LP_marketplace/blob/3ec9ffa1cd66fc54268de04fc9349709e37579d5/app.py#L7
почему-то зашит какой-то конкретный конфиг, и нельзя выбрать другой с помощью одной переменной.

Либо кто-то планировал менять конфиг на нужный прямо в коде, что на самом деле ужасный вариант, т.к. это может случайно попасть в репозиторий и всем все сломать.
Лябо вся настройка скатывается в вариант 2, но тут настолько много переменных, слабо отличимых друг от друга, что во временем неизбежно что-то точно пойдет не так.

Решений тут может быть два:
1. Убрать захардкоженное значение, если нужен вариант №1. Например, можно добавить config.py if с соответствующей проверкой - по значению переменной окружения возвращать разные классы из того же файла или читать другие файлы (например, поддерживаются cfg и yml конфиги).
2. Использовать более точные названия переменных окружения, если планировалось использовать вариант №2. Тут можно еще попробовать применить модуль dotenv, что по сути будет как текстовые конфиги.

Это не совсем уж критично, на первом этапе - пока что до production далеко, поэтому можно оставить один единственные development конфиг.
Но когда-нибудь это все же придется исправлять.

2020-10-03 16:11 UTC, merged