add model store
Anastasiella/LP_marketplace pull request #10
Opened 2020-10-28 02:02 UTC by Artork

add store model with relationship

2020-10-28 08:43 UTC, dolfinus requested changes

2020-10-28 08:43 UTC, dolfinus commented on marketplace/user/models.py
> +    store = relationship("Store", back_populates="seller")
Хм. В целом задумка интересная, чтобы получить store по продавцу или по товару, но обе эти модели могут быть связаны с несколькими строками в store. Поэтому предлагаю использовать здесь множественное число.
Не в самом store, там строка ссылается на вполне определенного продавца и вполне определенный товар. Я говорю именно про модели User и Good.

2020-10-29 03:09 UTC, Artork commented on marketplace/user/models.py
> +    store = relationship("Store", back_populates="seller")
Скорректировал

2020-10-29 08:48 UTC, dolfinus approved these changes

2020-10-29 09:12 UTC, merged