Удалил store добавил модель и форму и роут для cart
Anastasiella/LP_marketplace pull request #13
Opened 2020-11-10 03:15 UTC by Artork

реализация корзины без склада

2020-11-10 08:43 UTC, dolfinus requested changes

2020-11-10 08:43 UTC, dolfinus commented on marketplace/cart/models.py
> +    store_id = db.Column(db.Integer, db.ForeignKey('store.id'))
Store больше нет, колонку можно удалить

2020-11-10 08:43 UTC, dolfinus commented on marketplace/cart/models.py
> +        self.store_id  = store_id
И здесь тоже (кстати, `__init__` тут вообще можно удалить)

2020-11-10 08:43 UTC, dolfinus commented on marketplace/templates/cart/cart.html
> + <div class="row">
А почему div вместо table?

2020-11-10 08:43 UTC, dolfinus commented on marketplace/cart/forms.py
> +class CartForm(FlaskForm):
Это форма самой корзины. В ней должны быть кнопки оформления и отмены заказа (возможно в разных формах).

2020-11-10 08:43 UTC, dolfinus commented on marketplace/cart/forms.py
> +class CartItemForm(FlaskForm):
Это форма строки корзины. В ней должна быть кнопка удаления (мы договорились обойтись без редактирования количества).

То, что ты сейчас добавил, это форма под карточкой товара, которая должна отображаться на странице со списком товаров. Располагаться и называться она должна соответствующе, например по роуту `/categories/{category_id}` и называться GoodAddToCart,

2020-11-12 16:58 UTC, Artork commented on marketplace/cart/forms.py
> +class CartForm(FlaskForm):
скорректировал

2020-11-12 16:58 UTC, Artork commented on marketplace/cart/forms.py
> +class CartItemForm(FlaskForm):
исправил

2020-11-12 16:58 UTC, Artork commented on marketplace/templates/cart/cart.html
> + <div class="row">
Оставлю пока так, потом наведу красоту

2020-11-12 16:58 UTC, Artork commented on marketplace/cart/models.py
> +        self.store_id  = store_id
выполнено

2020-11-12 16:58 UTC, Artork commented on marketplace/cart/models.py
> +    store_id = db.Column(db.Integer, db.ForeignKey('store.id'))
удалил

2020-11-12 18:03 UTC, dolfinus approved these changes

2020-11-12 18:15 UTC, merged