Реализована модель регистрации, авторизации
Anastasiella/LP_marketplace pull request #3
Opened 2020-10-10 06:30 UTC by Artork

Подготовлена основа для регистрации и процессов login, logout.
Не смог разобраться с мультивыбором, саму форму подготовил, а как её засунуть в BD пока не понял.

2020-10-10 10:06 UTC, dolfinus requested changes
Так, а что за мультивыбор? Мы вроде договорились пока не решать задачу, когда пользователь является одновременно и продавцом, и покупателемю

2020-10-10 10:06 UTC, dolfinus commented on webapp/templates/user/registration.html
> +<html lang="ru">
Замени, пожалуйста, копипасту на extend базовго шаблона.

2020-10-10 10:06 UTC, dolfinus commented on webapp/user/views.py
> +def process_login():
Не обязательно создавать отдельный URL на обработку формы. Можно использовать тот же ``/login``, но у контроллера для отрисовки формы методом будет GET, а у контроллера для обработки отправленной формы - POST. Иначе можно утонуть во всех этих функциях.

2020-10-10 10:06 UTC, dolfinus commented on webapp/user/views.py
> +@blueprint.route('/process-reg', methods=['POST'])
Здесь аналогично пункту выше

2020-10-10 10:06 UTC, dolfinus commented on webapp/user/models.py
> +    email = db.Column(db.String(50))
А email разве не уникальный?

2020-10-10 10:06 UTC, dolfinus commented on requirements.txt
> +beautifulsoup4==4.9.1
Эта зависимость не нужна для проекта

2020-10-10 10:06 UTC, dolfinus commented on requirements.txt
> +soupsieve==2.0.1
И эта

2020-10-10 10:06 UTC, dolfinus commented on .gitignore
> +config.py
Не рекомендую добавлять в исключения файл с конфигом - там могут быть и параметры, которые не являются секретными, как пароли к БД, но от которых зависит работа приложения.

2020-10-10 10:09 UTC, dolfinus commented on webapp/__init__.py
> +    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
Не нужно изменять конфиг за пределами config.py

2020-10-12 16:15 UTC, Artork commented on webapp/user/views.py
> +def process_login():
Можно будет на данном этапе так оставить? Не разбирал еще метод GET боюсь на долго на нём зависнуть... Поправлю когда полностью пройду трек по web.

2020-10-12 16:17 UTC, Artork commented on webapp/user/models.py
> +    email = db.Column(db.String(50))
Скорректировал. Думаю еще потом flash добавить "Данный email занят"

2020-10-12 16:17 UTC, Artork commented on requirements.txt
> +beautifulsoup4==4.9.1
Убрал

2020-10-12 16:18 UTC, Artork commented on requirements.txt
> +soupsieve==2.0.1
Убрал

2020-10-12 16:18 UTC, Artork commented on .gitignore
> +config.py
Скорректировал

2020-10-12 16:18 UTC, Artork commented on webapp/__init__.py
> +    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
Убрал в config

2020-10-12 16:19 UTC, Artork commented on webapp/templates/user/registration.html
> +<html lang="ru">
Заменил на extend

2020-10-12 16:48 UTC, dolfinus commented on webapp/user/views.py
> +def process_login():
GET это метод по-умолчанию, его не нужно изучать)

2020-10-12 16:48 UTC, dolfinus commented on requirements.txt
> +beautifulsoup4==4.9.1
Что-то не заметил изменений.

2020-10-12 16:49 UTC, dolfinus commented on webapp/templates/user/registration.html
> +
Не делай такие большие отступы, пожалуйста

2020-10-12 16:49 UTC, dolfinus commented on webapp/user/forms.py
> +    my_choices = [('1', 'Покупатель'), ('2', 'Продавец')]
Вместо читаемых ролей тут все еще какие-то идентификаторы

2020-10-12 16:51 UTC, dolfinus commented on webapp/__init__.py
> +    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
Изменений не увидел

2020-10-12 16:51 UTC, dolfinus commented on webapp/config.py
> +SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, '..', 'webapp.db')
Ммм.. А почему файл отличается от того, что есть в мастере?

2020-10-12 16:56 UTC, dolfinus commented
Конфликты исправь

2020-10-20 07:55 UTC, closed without merging