внес правки в зацикливание после процесса логина, добавил сущность ад…
Anastasiella/LP_marketplace pull request #7
Opened 2020-10-19 02:11 UTC by Artork

Исправил зацикливание в процессе логина, добавил сущность админа

2020-10-19 07:56 UTC, dolfinus requested changes

2020-10-19 07:56 UTC, dolfinus commented on marketplace/admin/views.py
> +    return render_template('admin/index.html', page_title= title)
Идея создать страницу, которая видна чисто админу и больше не кому, имеет право на жизнь.
Но вот делать из нее исключительно страницу редактирования категорий не нужно, у админа ведь могут быть и другие функции.
Страница редактирования категорий должна располагаться в модуле категорий, просто не-админы должны видеть вместо нее уведомление о недостаточных правах. А эту страницу пока предлагаю удалить.

2020-10-23 18:26 UTC, Artork commented on marketplace/admin/views.py
> +    return render_template('admin/index.html', page_title= title)
принято, удалю при следующем коммите

2020-10-24 09:32 UTC, dolfinus requested changes

2020-10-24 09:32 UTC, dolfinus commented on marketplace/templates/base.html
> +          <a class="dropdown-item" href="{{ url_for('user.logout') }}">Выйти</a>
Делай теги более вложенными друг в друга, так их будет проще читать

2020-10-24 09:32 UTC, dolfinus commented on marketplace/templates/base.html
> +        {% endif %}
Если условие не сработает, то у тебя останется  только закрывающий тег ```</li>```, без открывающего. Нужно исправить.

2020-10-24 09:33 UTC, dolfinus commented on marketplace/admin/views.py
> +    return render_template('admin/index.html', page_title= title)
Что-то ничего не произошло

2020-10-24 16:07 UTC, Artork commented on marketplace/admin/views.py
> +    return render_template('admin/index.html', page_title= title)
удалил

2020-10-24 16:07 UTC, Artork commented on marketplace/templates/base.html
> +          <a class="dropdown-item" href="{{ url_for('user.logout') }}">Выйти</a>
Исправил

2020-10-24 16:07 UTC, Artork commented on marketplace/templates/base.html
> +        {% endif %}
скорректировал

2020-10-24 16:11 UTC, dolfinus requested changes

2020-10-24 16:11 UTC, dolfinus commented on marketplace/templates/base.html
> +              <a class="dropdown-item" href="{{ url_for('admin.admin_index') }}">Форма админа</a>
У тебя больше нет этого view. Ссылку нужно убрать

2020-10-24 16:21 UTC, dolfinus approved these changes

2020-10-24 16:23 UTC, merged