Goods view
Anastasiella/LP_marketplace pull request #9
Opened 2020-10-27 16:00 UTC by Anastasiella

2020-10-27 16:03 UTC, dolfinus commented on marketplace/goods/models.py
> +class Goods(db.Model):
Название модели должно быть в единственном числе, в отличие от таблицы.
Ты ведь пишешь:
```python
cucumber = Good(name='cucumber')
```
а не 
```python
cucumber = Goods(name='cucumber')
```

2020-10-27 16:03 UTC, dolfinus commented on marketplace/goods/models.py
> +    category_id = db.Column(db.Integer, db.ForeignKey('category.category_id'), nullable=False)
Нужно добавить поле типа relationship для категории

2020-10-27 16:10 UTC, dolfinus commented on marketplace/templates/goods/good_list.html
> +                 <div class="items-view border m-3 p-1 border-secondary rounded" id="parent_good">
id должен быть уникальным, а ты проставляешь его в цикле. нужно убрать

2020-10-27 16:11 UTC, dolfinus commented on marketplace/templates/category/item.html
> +      <p><a href="/goods/{{ category_id }}">{{ category }}</a></p>
А почему? Это ведь шаблон для отображения страницы категории, каждая карточка ссылается на страницу категории. И тут внезапно url ведет на страницу товара

2020-10-27 16:13 UTC, dolfinus commented on marketplace/goods/views.py
> +    def convert_data_to_hr_format(date_of_item):
Лучше сделать так: https://riptutorial.com/flask/example/4779/format-datetime-in-a-jinja2-template
У тебя ведь дата и время не только на страницах товаров будут форматироваться к нужному виду, пусть функция будет глобальной

2020-10-27 16:15 UTC, dolfinus commented on marketplace/templates/goods/good_list.html
> +                        <p>Создано: {{ convert_data_to_hr_format(item.created_at) }}</p>
Лучше назвать функцию не convert, а format.
convert - это для машиночитаемых представлений. Например, конвертировать можно один формат файла в другое.
format - это представление, чисто для пользователей.

2020-10-27 16:16 UTC, dolfinus commented on marketplace/goods/models.py
> +    quantity = db.Column(db.Integer)
Ммм, а как это у товара может быть количество? У записей на складе - ОК, у строк корзины - ОК, но вот у отдельно взятого товара "огурцы" нет количества.

2020-10-27 16:19 UTC, dolfinus requested changes
Поправь замечания, пожалуйста

2020-10-28 06:51 UTC, Anastasiella commented on marketplace/templates/category/item.html
> +      <p><a href="/goods/{{ category_id }}">{{ category }}</a></p>
У нас на этой странице отображается список товаров с этой категорией, которые рендерятся во вью товаров. Мне показалось, что так будет логичнее

2020-10-28 08:28 UTC, dolfinus commented on marketplace/templates/category/item.html
> +      <p><a href="/goods/{{ category_id }}">{{ category }}</a></p>
url выглядит как ```/goods/123```. Из этого не понятно. что 123 - это не идентификатор товара, а идентификатор категории.
Предлагаю такой вариант:
* `/categories` - список категорий
* `/categories/123` - страница категори (список товаров в ней)
* `/goods/345` - страница товара

2020-10-28 08:35 UTC, dolfinus commented on marketplace/utils/filters.py
> +def format_data_to_hr(date_of_item):
А что такое hr?)

2020-10-28 08:38 UTC, dolfinus commented
Остались нерешенными вопросы по relationship и по путям и шаблонам страниц категорий.

2020-10-28 20:35 UTC, dolfinus commented on marketplace/goods/views.py
> +@goods_blueprint.route('/', methods=['GET'], strict_slashes=False)
Ммм, а почему именно так, а не предыдущий вариант с параметром в url?

2020-10-28 20:38 UTC, dolfinus commented on marketplace/templates/category/item.html
> +      <p><a href="/goods/?category={{ category_id }}">{{ category }}</a></p>
Url снова ведут в /goods вместо /categories

2020-10-29 08:51 UTC, merged